# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('analytics_report_type', models.CharField(max_length=50)),
                ('analytics_period_start', models.DateField()),
                ('analytics_period_end', models.DateField()),
                ('analytics_total_orders', models.IntegerField(blank=True, null=True)),
                ('analytics_total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('analytics_total_customers', models.IntegerField(blank=True, null=True)),
                ('analytics_avg_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('analytics_generated_at', models.DateTimeField(blank=True, null=True)),
                ('analytics_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('feedback_responded', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviews_rating', models.IntegerField()),
                ('reviews_comment', models.TextField(blank=True, null=True)),
                ('reviews_date', models.DateTimeField(blank=True, null=True)),
                ('reviews_approved', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
