# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_history_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orderhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_items_quantity', models.IntegerField()),
                ('order_items_price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orderitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_date', models.DateTimeField(blank=True, null=True)),
                ('orders_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstatuses',
            fields=[
                ('order_statuses_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_statuses_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'orderstatuses',
                'managed': False,
            },
        ),
    ]
