# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('addresses_id', models.AutoField(primary_key=True, serialize=False)),
                ('addresses_street', models.CharField(max_length=255)),
                ('addresses_city', models.CharField(max_length=100)),
                ('addresses_zip_code', models.CharField(max_length=20)),
                ('addresses_country', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses_is_default', models.BooleanField(blank=True, null=True)),
                ('addresses_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roles_id', models.AutoField(primary_key=True, serialize=False)),
                ('roles_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userroles',
            fields=[
                ('user_roles_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_roles_assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userroles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('users_email', models.CharField(max_length=255, unique=True)),
                ('users_password_hash', models.CharField(max_length=255)),
                ('users_first_name', models.CharField(max_length=100)),
                ('users_last_name', models.CharField(max_length=100)),
                ('users_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('users_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('users_secret_word', models.CharField(blank=True, max_length=255, null=True)),
                ('users_created_at', models.DateTimeField(blank=True, null=True)),
                ('users_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
