# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('cart_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_items_quantity', models.IntegerField()),
                ('cart_items_added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cartitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('carts_id', models.AutoField(primary_key=True, serialize=False)),
                ('carts_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carts',
                'managed': False,
            },
        ),
    ]
