# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brands_id', models.AutoField(primary_key=True, serialize=False)),
                ('brands_name', models.CharField(max_length=100, unique=True)),
                ('brands_description', models.TextField(blank=True, null=True)),
                ('brands_logo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=100, unique=True)),
                ('categories_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productcharacteristics',
            fields=[
                ('product_characteristics_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_characteristics_key', models.CharField(max_length=100)),
                ('product_characteristics_value', models.TextField()),
            ],
            options={
                'db_table': 'productcharacteristics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productimages',
            fields=[
                ('product_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_images_url', models.CharField(max_length=255)),
                ('product_images_is_main', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=255)),
                ('products_description', models.TextField(blank=True, null=True)),
                ('products_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_stock', models.IntegerField()),
                ('products_created_at', models.DateTimeField(blank=True, null=True)),
                ('products_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
