# Generated by Django 5.2.2 on 2025-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverymethods',
            fields=[
                ('delivery_methods_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_methods_name', models.CharField(max_length=100, unique=True)),
                ('delivery_methods_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_methods_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deliverymethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentmethods',
            fields=[
                ('payment_methods_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_methods_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'paymentmethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payments_id', models.AutoField(primary_key=True, serialize=False)),
                ('payments_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payments_date', models.DateTimeField(blank=True, null=True)),
                ('payments_status', models.CharField(max_length=50)),
                ('payments_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
